import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpToLine,
  CheckCheck,
  CircleHelp,
  ClipboardPaste,
  Command,
  Copy,
  CopySlash,
  Download,
  Eye,
  FolderOpen,
  FolderPlus,
  Globe,
  Hand,
  Keyboard,
  Languages,
  LayoutGrid,
  Info,
  Link2,
  ListChecks,
  Moon,
  Pencil,
  RefreshCw,
  Scissors,
  Settings,
  Square,
  Terminal,
  Trash2,
  Unplug,
  Upload,
  X,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  "view.open-command-palette": Command,
  "view.toggle-dot-entries": Eye,
  "view.toggle-listing-mode": LayoutGrid,
  "view.apply-global-listing-settings": Globe,
  "appearance.cycle-theme": Moon,
  "appearance.cycle-ui-mode": Hand,
  "appearance.set-locale": Languages,
  "appearance.set-theme": Moon,
  "appearance.set-ui-mode": Hand,
  "navigation.back": ArrowLeft,
  "navigation.forward": ArrowRight,
  "navigation.refresh": RefreshCw,
  "navigation.cancel-load": X,
  "navigation.focus-quick-filter": Eye,
  "navigation.open": ArrowRight,
  "navigation.up": ArrowUpToLine,
  "navigation.open-settings": Settings,
  "navigation.go-to-path": FolderOpen,
  "selection.move-down": ArrowDown,
  "selection.move-up": ArrowUp,
  "selection.move-left": ArrowLeft,
  "selection.move-right": ArrowRight,
  "selection.toggle": Square,
  "selection.select-all": CheckCheck,
  "selection.clear": X,
  "selection.toggle-mode": ListChecks,
  "selection.copy-paths": CopySlash,
  "selection.download": Download,
  "file.new-folder": FolderPlus,
  "file.rename": Pencil,
  "file.copy": Copy,
  "file.cut": Scissors,
  "file.paste": ClipboardPaste,
  "file.delete": Trash2,
  "file.upload-open-panel": Upload,
  "file.upload-choose-files": Upload,
  "preview.get-info": Info,
  "viewer.preview": Eye,
  "cloud.share-url": Link2,
  "cloud.disconnect": Unplug,
  "help.open-keyboard-shortcuts": Keyboard,
  "help.open-about": CircleHelp,
};

export function actionIcon(id: string): LucideIcon | null {
  return ICONS[id] ?? null;
}

export function actionIconWithFallback(id: string): LucideIcon {
  return ICONS[id] ?? Terminal;
}
